Upload distribution files from CI to S3

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,7 +1,25 @@
 #!/bin/sh
 
-set -ex
+set -e
+
+S3_CREDENTIALS_FILE=/var/lib/jenkins/config/s3credentials
+
+cd "$(dirname $0)/.."
+
+if [ ! -f "${S3_CREDENTIALS_FILE}" ]; then
+  echo >&2 "Error: Can't find ${S3_CREDENTIALS_FILE}"
+  exit 1
+fi
+
+. "${S3_CREDENTIALS_FILE}"
+
+export LIBCHROMIUMCONTENT_S3_BUCKET="${JANKY_ARTIFACTS_S3_BUCKET}"
+export LIBCHROMIUMCONTENT_S3_ACCESS_KEY="${JANKY_ARTIFACTS_S3_ACCESS_KEY}"
+export LIBCHROMIUMCONTENT_S3_SECRET_KEY="${JANKY_ARTIFACTS_S3_SECRET_KEY}"
+
+set -x
 
 script/bootstrap
 script/build
 script/create-dist
+script/upload
